
version: '3.7'

services:
  database:
    image: eu.gcr.io/altipla-tools/mysql:latest
    ports: ['3306:3306']

  redis:
    image: redis:5
    ports: ['6379:6379']

  phpmyadmin:
    image: eu.gcr.io/altipla-tools/phpmyadmin:latest
    ports: ['5000:80']

  firestore:
    image: eu.gcr.io/altipla-tools/firestore:latest
    ports: ['12000:12000']

  ravendb:
    image: ravendb/ravendb:4.2.104-ubuntu.18.04-x64
    ports: ['13000:8080']
    stop_signal: SIGKILL
    environment:
      RAVEN_Setup_Mode: 'None'
      RAVEN_License_Eula_Accepted: 'true'
      RAVEN_Security_UnsecuredAccessAllowed: PrivateNetwork
