// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/pagination/pagination.proto

package pagination // import "libs.altipla.consulting/protos/pagination"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status struct {
	ParamsChecksum       string   `protobuf:"bytes,1,opt,name=params_checksum,json=paramsChecksum,proto3" json:"params_checksum,omitempty"`
	Cursor               string   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_d70d5df117fd52c6, []int{0}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetParamsChecksum() string {
	if m != nil {
		return m.ParamsChecksum
	}
	return ""
}

func (m *Status) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func init() {
	proto.RegisterType((*Status)(nil), "libs.pagination.Status")
}

func init() {
	proto.RegisterFile("protos/pagination/pagination.proto", fileDescriptor_pagination_d70d5df117fd52c6)
}

var fileDescriptor_pagination_d70d5df117fd52c6 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x48, 0x4c, 0xcf, 0xcc, 0x4b, 0x2c, 0xc9, 0xcc, 0xcf, 0x43, 0x62, 0xea,
	0x81, 0x25, 0x85, 0xf8, 0x73, 0x32, 0x93, 0x8a, 0xf5, 0x10, 0xc2, 0x4a, 0x9e, 0x5c, 0x6c, 0xc1,
	0x25, 0x89, 0x25, 0xa5, 0xc5, 0x42, 0xea, 0x5c, 0xfc, 0x05, 0x89, 0x45, 0x89, 0xb9, 0xc5, 0xf1,
	0xc9, 0x19, 0xa9, 0xc9, 0xd9, 0xc5, 0xa5, 0xb9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x7c,
	0x10, 0x61, 0x67, 0xa8, 0xa8, 0x90, 0x18, 0x17, 0x5b, 0x72, 0x69, 0x51, 0x71, 0x7e, 0x91, 0x04,
	0x13, 0x58, 0x1e, 0xca, 0x73, 0xd2, 0x8e, 0xd2, 0x04, 0x9b, 0x9e, 0x98, 0x53, 0x92, 0x59, 0x90,
	0x93, 0xa8, 0x97, 0x9c, 0x9f, 0x57, 0x5c, 0x9a, 0x53, 0x92, 0x99, 0x97, 0xae, 0x8f, 0xe1, 0xb2,
	0x24, 0x36, 0xb0, 0x90, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x3b, 0x16, 0x8b, 0xb5, 0x00,
	0x00, 0x00,
}
