// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/bigquery/proto/pagination.proto

package libs_bigquery

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Token struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Checksum             int64    `protobuf:"varint,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_58886fd80a300e1e, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *Token) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *Token) GetChecksum() int64 {
	if m != nil {
		return m.Checksum
	}
	return 0
}

func init() {
	proto.RegisterType((*Token)(nil), "libs.bigquery.Token")
}

func init() {
	proto.RegisterFile("pkg/bigquery/proto/pagination.proto", fileDescriptor_58886fd80a300e1e)
}

var fileDescriptor_58886fd80a300e1e = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0xc8, 0x4e, 0xd7,
	0x4f, 0xca, 0x4c, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f,
	0x48, 0x4c, 0xcf, 0xcc, 0x4b, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x03, 0x0b, 0x08, 0xf1, 0xe6, 0x64,
	0x26, 0x15, 0xeb, 0xc1, 0x54, 0x29, 0x45, 0x72, 0xb1, 0x86, 0xe4, 0x67, 0xa7, 0xe6, 0x09, 0x89,
	0x72, 0xb1, 0x65, 0xe5, 0x27, 0xc5, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xb1,
	0x66, 0xe5, 0x27, 0x79, 0xa6, 0x08, 0xc9, 0x72, 0x71, 0x15, 0x24, 0xa6, 0xa7, 0xc6, 0x97, 0x80,
	0x14, 0x49, 0x30, 0x81, 0xa5, 0x38, 0x41, 0x22, 0x10, 0x5d, 0x52, 0x5c, 0x1c, 0xc9, 0x19, 0xa9,
	0xc9, 0xd9, 0xc5, 0xa5, 0xb9, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x70, 0x7e, 0x12, 0x1b,
	0xd8, 0x42, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x16, 0x58, 0x79, 0x3d, 0x97, 0x00, 0x00,
	0x00,
}
