// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`en`] = []string{
		`---`,
		`Jan`,
		`Feb`,
		`Mar`,
		`Apr`,
		`May`,
		`Jun`,
		`Jul`,
		`Aug`,
		`Sep`,
		`Oct`,
		`Nov`,
		`Dec`,
	}

	LongMonthNames[`en`] = []string{
		`---`,
		`January`,
		`February`,
		`March`,
		`April`,
		`May`,
		`June`,
		`July`,
		`August`,
		`September`,
		`October`,
		`November`,
		`December`,
	}

	ShortWeekdays[`en`] = []string{
		`Sun`,
		`Mon`,
		`Tue`,
		`Wed`,
		`Thu`,
		`Fri`,
		`Sat`,
	}

	LongWeekdays[`en`] = []string{
		`Sunday`,
		`Monday`,
		`Tuesday`,
		`Wednesday`,
		`Thursday`,
		`Friday`,
		`Saturday`,
	}

}
