// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`es`] = []string{
		`---`,
		`ene.`,
		`feb.`,
		`mar.`,
		`abr.`,
		`may.`,
		`jun.`,
		`jul.`,
		`ago.`,
		`sept.`,
		`oct.`,
		`nov.`,
		`dic.`,
	}

	LongMonthNames[`es`] = []string{
		`---`,
		`enero`,
		`febrero`,
		`marzo`,
		`abril`,
		`mayo`,
		`junio`,
		`julio`,
		`agosto`,
		`septiembre`,
		`octubre`,
		`noviembre`,
		`diciembre`,
	}

	ShortWeekdays[`es`] = []string{
		`dom.`,
		`lun.`,
		`mar.`,
		`mié.`,
		`jue.`,
		`vie.`,
		`sáb.`,
	}

	LongWeekdays[`es`] = []string{
		`domingo`,
		`lunes`,
		`martes`,
		`miércoles`,
		`jueves`,
		`viernes`,
		`sábado`,
	}

}
