// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`fr`] = []string{
		`---`,
		`janv.`,
		`févr.`,
		`mars`,
		`avr.`,
		`mai`,
		`juin`,
		`juil.`,
		`août`,
		`sept.`,
		`oct.`,
		`nov.`,
		`déc.`,
	}

	LongMonthNames[`fr`] = []string{
		`---`,
		`janvier`,
		`février`,
		`mars`,
		`avril`,
		`mai`,
		`juin`,
		`juillet`,
		`août`,
		`septembre`,
		`octobre`,
		`novembre`,
		`décembre`,
	}

	ShortWeekdays[`fr`] = []string{
		`dim.`,
		`lun.`,
		`mar.`,
		`mer.`,
		`jeu.`,
		`ven.`,
		`sam.`,
	}

	LongWeekdays[`fr`] = []string{
		`dimanche`,
		`lundi`,
		`mardi`,
		`mercredi`,
		`jeudi`,
		`vendredi`,
		`samedi`,
	}

}
