// Package symbols contains the autogenerated i18n symbols for formatting.
package symbols

var (
	ShortMonthNames = map[string][]string{}
	LongMonthNames  = map[string][]string{}

	LongWeekdays  = map[string][]string{}
	ShortWeekdays = map[string][]string{}
)
