// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`it`] = []string{
		`---`,
		`gen`,
		`feb`,
		`mar`,
		`apr`,
		`mag`,
		`giu`,
		`lug`,
		`ago`,
		`set`,
		`ott`,
		`nov`,
		`dic`,
	}

	LongMonthNames[`it`] = []string{
		`---`,
		`gennaio`,
		`febbraio`,
		`marzo`,
		`aprile`,
		`maggio`,
		`giugno`,
		`luglio`,
		`agosto`,
		`settembre`,
		`ottobre`,
		`novembre`,
		`dicembre`,
	}

	ShortWeekdays[`it`] = []string{
		`dom`,
		`lun`,
		`mar`,
		`mer`,
		`gio`,
		`ven`,
		`sab`,
	}

	LongWeekdays[`it`] = []string{
		`domenica`,
		`lunedì`,
		`martedì`,
		`mercoledì`,
		`giovedì`,
		`venerdì`,
		`sabato`,
	}

}
