// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`ja`] = []string{
		`---`,
		`1月`,
		`2月`,
		`3月`,
		`4月`,
		`5月`,
		`6月`,
		`7月`,
		`8月`,
		`9月`,
		`10月`,
		`11月`,
		`12月`,
	}

	LongMonthNames[`ja`] = []string{
		`---`,
		`1月`,
		`2月`,
		`3月`,
		`4月`,
		`5月`,
		`6月`,
		`7月`,
		`8月`,
		`9月`,
		`10月`,
		`11月`,
		`12月`,
	}

	ShortWeekdays[`ja`] = []string{
		`日`,
		`月`,
		`火`,
		`水`,
		`木`,
		`金`,
		`土`,
	}

	LongWeekdays[`ja`] = []string{
		`日曜日`,
		`月曜日`,
		`火曜日`,
		`水曜日`,
		`木曜日`,
		`金曜日`,
		`土曜日`,
	}

}
