// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`pt`] = []string{
		`---`,
		`jan`,
		`fev`,
		`mar`,
		`abr`,
		`mai`,
		`jun`,
		`jul`,
		`ago`,
		`set`,
		`out`,
		`nov`,
		`dez`,
	}

	LongMonthNames[`pt`] = []string{
		`---`,
		`janeiro`,
		`fevereiro`,
		`março`,
		`abril`,
		`maio`,
		`junho`,
		`julho`,
		`agosto`,
		`setembro`,
		`outubro`,
		`novembro`,
		`dezembro`,
	}

	ShortWeekdays[`pt`] = []string{
		`dom`,
		`seg`,
		`ter`,
		`qua`,
		`qui`,
		`sex`,
		`sáb`,
	}

	LongWeekdays[`pt`] = []string{
		`domingo`,
		`segunda-feira`,
		`terça-feira`,
		`quarta-feira`,
		`quinta-feira`,
		`sexta-feira`,
		`sábado`,
	}

}
