// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/datetime/datetime.proto

package datetime

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Date struct {
	Day                  int32    `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Year                 int32    `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_949572a023539668, []int{0}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

type DateRange struct {
	Start                *Date    `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *Date    `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateRange) Reset()         { *m = DateRange{} }
func (m *DateRange) String() string { return proto.CompactTextString(m) }
func (*DateRange) ProtoMessage()    {}
func (*DateRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_949572a023539668, []int{1}
}

func (m *DateRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateRange.Unmarshal(m, b)
}
func (m *DateRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateRange.Marshal(b, m, deterministic)
}
func (m *DateRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateRange.Merge(m, src)
}
func (m *DateRange) XXX_Size() int {
	return xxx_messageInfo_DateRange.Size(m)
}
func (m *DateRange) XXX_DiscardUnknown() {
	xxx_messageInfo_DateRange.DiscardUnknown(m)
}

var xxx_messageInfo_DateRange proto.InternalMessageInfo

func (m *DateRange) GetStart() *Date {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *DateRange) GetEnd() *Date {
	if m != nil {
		return m.End
	}
	return nil
}

type DateRanges struct {
	Ranges               []*DateRange `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DateRanges) Reset()         { *m = DateRanges{} }
func (m *DateRanges) String() string { return proto.CompactTextString(m) }
func (*DateRanges) ProtoMessage()    {}
func (*DateRanges) Descriptor() ([]byte, []int) {
	return fileDescriptor_949572a023539668, []int{2}
}

func (m *DateRanges) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateRanges.Unmarshal(m, b)
}
func (m *DateRanges) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateRanges.Marshal(b, m, deterministic)
}
func (m *DateRanges) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateRanges.Merge(m, src)
}
func (m *DateRanges) XXX_Size() int {
	return xxx_messageInfo_DateRanges.Size(m)
}
func (m *DateRanges) XXX_DiscardUnknown() {
	xxx_messageInfo_DateRanges.DiscardUnknown(m)
}

var xxx_messageInfo_DateRanges proto.InternalMessageInfo

func (m *DateRanges) GetRanges() []*DateRange {
	if m != nil {
		return m.Ranges
	}
	return nil
}

func init() {
	proto.RegisterType((*Date)(nil), "libs.datetime.Date")
	proto.RegisterType((*DateRange)(nil), "libs.datetime.DateRange")
	proto.RegisterType((*DateRanges)(nil), "libs.datetime.DateRanges")
}

func init() { proto.RegisterFile("protos/datetime/datetime.proto", fileDescriptor_949572a023539668) }

var fileDescriptor_949572a023539668 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x59, 0xd3, 0x2d, 0x38, 0x45, 0x90, 0xd1, 0x43, 0x4e, 0x52, 0x16, 0xc4, 0xf6, 0x92,
	0x4a, 0xbd, 0x7b, 0x28, 0xfe, 0x82, 0x3d, 0x0a, 0x1e, 0xa6, 0x6e, 0xa8, 0x81, 0x6c, 0xb2, 0x24,
	0xe3, 0x61, 0xff, 0xbd, 0x64, 0x56, 0x17, 0x14, 0x7b, 0x7b, 0x79, 0xef, 0xcb, 0x17, 0x08, 0xdc,
	0x0d, 0x29, 0x72, 0xcc, 0xbb, 0x8e, 0xd8, 0xb2, 0xeb, 0xed, 0x1c, 0x8c, 0x0c, 0x78, 0xe5, 0xdd,
	0x31, 0x9b, 0x9f, 0xb2, 0x39, 0xc0, 0xe2, 0x85, 0xd8, 0xe2, 0x35, 0xa8, 0x8e, 0x46, 0x5d, 0xad,
	0xab, 0x4d, 0xdd, 0x96, 0x88, 0xb7, 0x50, 0xf7, 0x31, 0xf0, 0x87, 0xbe, 0x90, 0x6e, 0x3a, 0x20,
	0xc2, 0x62, 0xb4, 0x94, 0xb4, 0x92, 0x52, 0x72, 0xf3, 0x06, 0x97, 0xc5, 0xd1, 0x52, 0x38, 0x59,
	0xdc, 0x42, 0x9d, 0x99, 0x12, 0x8b, 0x6a, 0xb5, 0xbf, 0x31, 0xbf, 0xde, 0x33, 0x02, 0x4e, 0x04,
	0xde, 0x83, 0xb2, 0xa1, 0x13, 0xff, 0x19, 0xb0, 0xec, 0xcd, 0x33, 0xc0, 0xac, 0xcf, 0xf8, 0x08,
	0xcb, 0x24, 0x49, 0x57, 0x6b, 0xb5, 0x59, 0xed, 0xf5, 0x7f, 0xf7, 0x0a, 0xd0, 0x7e, 0x73, 0x87,
	0xed, 0xeb, 0x83, 0x20, 0xe4, 0xd9, 0x0d, 0x9e, 0xcc, 0x7b, 0x0c, 0xf9, 0xd3, 0xb3, 0x0b, 0xa7,
	0xdd, 0x9f, 0xbf, 0x3a, 0x2e, 0xa5, 0x78, 0xfa, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x8b, 0x28,
	0xaf, 0x45, 0x01, 0x00, 0x00,
}
