
name: PR check
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  pr-check:
    strategy:
      matrix:
        go-version: [1.14.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go-version}}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start services
      run: docker-compose up -d redis database firestore

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: go-${{ runner.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: go-${{ runner.go-version }}-

    - name: Lint
      run: make lint

    - name: Test
      run: go test -race ./...

    - name: Stop services
      if: always()
      run: docker-compose kill
