// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`de`] = []string{
		`---`,
		`Jan.`,
		`Feb.`,
		`März`,
		`Apr.`,
		`Mai`,
		`Juni`,
		`Juli`,
		`Aug.`,
		`Sep.`,
		`Okt.`,
		`Nov.`,
		`Dez.`,
	}

	LongMonthNames[`de`] = []string{
		`---`,
		`Januar`,
		`Februar`,
		`März`,
		`April`,
		`Mai`,
		`Juni`,
		`Juli`,
		`August`,
		`September`,
		`Oktober`,
		`November`,
		`Dezember`,
	}

	ShortWeekdays[`de`] = []string{
		`So.`,
		`Mo.`,
		`Di.`,
		`Mi.`,
		`Do.`,
		`Fr.`,
		`Sa.`,
	}

	LongWeekdays[`de`] = []string{
		`Sonntag`,
		`Montag`,
		`Dienstag`,
		`Mittwoch`,
		`Donnerstag`,
		`Freitag`,
		`Samstag`,
	}

}
